spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_triaje
spring.datasource.username=postgres
spring.datasource.password=mamacoco8089
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8081
server.address=0.0.0.0
